[build]
  command = "./build.sh"
  publish = "export/html5/bin"

[build.environment]
  HAXE_VERSION = "4.3.2"
  LIME_VERSION = "8.1.3"
  OPENFL_VERSION = "9.3.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200